env:
  otlp:
    enabled: true

logging.level:
  org.springframework: info
    #transaction: info
    #security: trace
    #context.support.ResourceBundleMessageSource: DEBUG

server:
  port: 8081
    
spring:
  messages:
    basename: fw-messages
    encoding: UTF-8
  profiles:
    default: item,reservation,user
      
rms:
  log:
    server:
      enable: false
  resources:
    item: classpath:/json/item.json
    reservation: classpath:/json/reservation.json
    user: classpath:/json/user.json
